### PR TITLE
Order alphabetically

### PR DESCRIPTION
**Pull request by lexcast**

### CODE REVIEW

**Comment by EmanueleMinotto** [comment]
Thanks @lexcast, this is a really big change, could you split it into many commits, please?

**Comment by lexcast** [comment]
Im not sure if I can split in many commits, maybe in 2, one for order the table of contents and another for order all the categories.

**Comment by EmanueleMinotto** [comment]
the best thing would be:
* a commit for categories index sorting
* a commit for each category' sorting

PS: do a rebase

**Comment by lexcast** [comment]
Alright, sounds fine.

I will do it later in the day.

**Comment by TomasVotruba** [comment]
Ping @lexcast 

Good idea btw

**Comment by lexcast** [comment]
Sorry for the delay :sweat_smile: I forgot this

**Comment by TomasVotruba** [comment]
@lexcast Thank you :)

**Comment by EmanueleMinotto** [comment]
Thanks @lexcast, well done :+1:

**Pull request merged**
